[tool.poetry]
name = "python-project-52"
version = "0.1.0"
description = "task manager"
authors = ["nickolay_kuzmin <nickolay.kuzmin2001@gmail.com>"]
readme = "README.md"
packages = [{include = "python_project_52"}]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^1.0.0"
dj-database-url = "^2.0.0"
Django = "^4.2.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
