# Generated by Django 3.2.21 on 2023-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_created_at'),
        ('tasks', '0005_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='labels.Label', verbose_name='Label'),
        ),
    ]
